language: cpp
compiler:
  - gcc
before_install:
  - sudo add-apt-repository -y ppa:ubuntu-sdk-team/ppa
  - sudo add-apt-repository -y ppa:george-edison55/gcc4.7-precise
  - sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test
  - sudo apt-get update
install:
  - sudo apt-get install libboost-program-options-dev libboost-test-dev gcc-4.7 g++-4.7
  - sudo apt-get install cmake
  - sudo pip install lit
# Initialise our submodules
  - git submodule init
  - git submodule update
  - mkdir build && cd build
  - CC="gcc-4.7" CXX="g++-4.7" cmake -DENABLE_TESTING=ON ..
script:
  - make
  - test -f lib/libcryptominisat4.so
  - test -f ./cryptominisat
  - ctest -V
  - sudo make install
